### ISSUE TITLE
Failling on JRuby 9K

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-unix#23]
https://travis-ci.org/logstash-plugins/logstash-input-unix/jobs/236451211

``` 
 1) LogStash::Inputs::Unix when interrupting the plugin #client when the unix socket has no data to be read behaves like an interruptible input plugin #stop returns from run
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected `#<Thread:0x22cd8ec2@/home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-devutils-1.3.2-java/lib/logstash/devutils/rspec/shared_examples.rb:11 sleep>.alive?` to return false, got true
     Shared Example Group: "an interruptible input plugin" called from ./spec/inputs/unix_spec.rb:57
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:36:in `block in not_to'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:36:in `not_to'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/logstash-devutils-1.3.2-java/lib/logstash/devutils/rspec/shared_examples.rb:18:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.9.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 4.7 seconds (files took 3.18 seconds to load)
5 examples, 1 failure
```

**Comment by kares** [comment]
closing defunct issue
